require("dotenv").config();
const express=require("express");
const mongoose=require("mongoose");
const cors=require("cors");
const authRoutes=require("./routes/auth");
const hotelRoutes=require("./routes/hotels");
const bookingRoutes=require("./routes/bookings");
const app=express();
app.use(cors());app.use(express.json());
mongoose.connect(process.env.MONGODB_URI || "mongodb://127.0.0.1:27017/hotelDB");
app.use("/api/auth",authRoutes);
app.use("/api/hotels",hotelRoutes);
app.use("/api/bookings",bookingRoutes);
const PORT = process.env.PORT || 5000;
app.listen(PORT,()=>console.log("Server running on port "+PORT));